import React,{useEffect,useState}from'react';import{createRoot}from'react-dom/client';import{Menu,X,ArrowUpRight,ChevronDown,Instagram,Facebook,Mail,Phone,MapPin,Clock,Sparkles,Gift,Heart,CalendarDays}from'lucide-react';import'./styles.css';

const treatments=[['01','The Gift Ritual','90 min','£145','A slow, grounding journey combining warm oils, scalp massage and restorative facial work.'],['02','Deep Rest Massage','60 min','£95','Targeted full-body massage designed to release everyday tension and leave you deeply rested.'],['03','Botanical Facial','60 min','£110','A personalised facial using botanical textures, facial massage and a quiet finishing ritual.'],['04','Couples Escape','90 min','£260','A shared treatment experience for two, with time to reconnect before and after your rituals.'],['05','Mother & Daughter','75 min','£220','A gentle shared escape designed around connection, conversation and unhurried care.'],['06','The Little Reset','45 min','£72','A shorter ritual for busy weeks: shoulders, scalp, face and hands, finished with tea.']];

const gifts=[['A Quiet Hour','£95','A 60-minute restorative treatment.'],['The Full Ritual','£145','Our signature 90-minute spa experience.'],['For Two','£260','A shared 90-minute escape for two.'],['The Spa Edit','£195','Treatment plus a curated home-care gift box.']];

function Link({to,children,className=''}){return <a className={className} href={to}>{children}</a>}
function Layout({children}){const[open,setOpen]=useState(false);const[book,setBook]=useState(false);useEffect(()=>{window.scrollTo(0,0)},[location.pathname]);const nav=['Treatments','Gifting','Wellness','About','Journal','Gallery','Media','Contact'];return <><header><Link to="/" className="brand"><span>GIFT</span><i>SPA</i></Link><nav>{nav.map(n=><Link key={n} to={'/'+n.toLowerCase()}>{n}</Link>)}</nav><button className="bookBtn" onClick={()=>setBook(true)}>Book a visit <ArrowUpRight size={15}/></button><button className="menu" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button></header>{open&&<div className="mobileNav">{nav.map(n=><Link key={n} to={'/'+n.toLowerCase()} onClick={()=>setOpen(false)}>{n}</Link>)}<button onClick={()=>{setOpen(false);setBook(true)}}>Book a visit <ArrowUpRight size={16}/></button></div>}<main>{children}</main><footer><div className="footerTop"><div><div className="brand big"><span>GIFT</span><i>SPA</i></div><p>Time well given.<br/>A modern spa for slower days.</p></div><div><small>EXPLORE</small><Link to="/treatments">Treatments</Link><Link to="/gifting">Gift cards</Link><Link to="/wellness">Wellness</Link><Link to="/journal">Journal</Link></div><div><small>VISIT</small><p>42 Rose Lane<br/>London, UK</p><p>Mon–Sun · 09:00–20:00</p></div><div><small>CONTACT</small><a href="tel:+442079460880"><Phone size={14}/> +44 20 7946 0880</a><a href="mailto:hello@giftspa.co.uk"><Mail size={14}/> hello@giftspa.co.uk</a><div className="social"><Instagram/><Facebook/></div></div></div><div className="footerBottom"><span>© 2026 Gift Spa. All rights reserved.</span><div><Link to="/privacy">Privacy</Link><Link to="/terms">Terms</Link><Link to="/accessibility">Accessibility</Link></div></div></footer>{book&&<Booking close={()=>setBook(false)}/>}</>}

function Booking({close}){const[sent,setSent]=useState(false);return <div className="modal" onMouseDown={e=>e.target===e.currentTarget&&close()}><div className="booking"><button className="close" onClick={close}><X/></button>{sent?<><Sparkles className="modalIcon"/><h2>Your request is on its way.</h2><p>Thank you. Our guest team will be in touch to confirm your preferred time.</p><button className="primary" onClick={close}>Back to Gift Spa</button></>:<><small>PRIVATE BOOKING</small><h2>Choose your escape.</h2><p>Tell us what you are looking for and our team will confirm availability.</p><form onSubmit={e=>{e.preventDefault();setSent(true)}}><input required placeholder="Your name"/><input required type="email" placeholder="Email address"/><select><option>Choose a treatment</option>{treatments.map(t=><option key={t[0]}>{t[1]}</option>)}</select><input type="date"/><select><option>Preferred time</option><option>Morning</option><option>Afternoon</option><option>Evening</option></select><button className="primary">Request booking <ArrowUpRight size={16}/></button></form></>}</div></div>}

function Hero(){return <section className="hero"><div className="heroCopy"><p className="eyebrow">A MODERN UK SPA · LONDON</p><h1>Time well<br/><em>given.</em></h1><p className="lead">Thoughtful treatments, beautiful spaces and meaningful gifts designed to make slowing down feel effortless.</p><div className="actions"><Link className="primary" to="/treatments">Explore treatments <ArrowUpRight size={16}/></Link><Link className="textLink" to="/gifting">Give the gift of time <Gift size={16}/></Link></div></div><div className="heroVisual"><div className="orb orb1"/><div className="orb orb2"/><div className="heroCard"><span>01 — 06</span><strong>RESTORE<br/>YOUR RITUAL</strong><small>OPEN DAILY · 09—20</small></div></div></section>}

function Home(){return <><Hero/><section className="intro split"><div><p className="eyebrow">THE GIFT SPA APPROACH</p><h2>Wellness should feel like a <em>gift,</em> not another task.</h2></div><div><p>We created Gift Spa for the moments between everything else. Every treatment is intentionally unhurried, every detail considered, and every visit built around how you want to feel when you leave.</p><Link className="under" to="/about">Discover our approach <ArrowUpRight size={14}/></Link></div></section><section className="featureBand"><div><small>01 / SIGNATURE</small><h2>The Gift Ritual</h2><p>90 minutes of warm oils, skilled hands and stillness. Our most-loved experience.</p><Link className="under light" to="/treatments">Discover the ritual <ArrowUpRight size={14}/></Link></div><div className="featureImage"><span>GIFT SPA / 2026</span></div></section><section className="cardsSection"><div className="sectionHead"><div><p className="eyebrow">TREATMENTS</p><h2>Choose your pace.</h2></div><Link className="under" to="/treatments">View all <ArrowUpRight size={14}/></Link></div><div className="cards">{treatments.slice(0,3).map(t=><TreatmentCard key={t[0]} t={t}/>)}</div></section><section className="quote"><span>“</span><blockquote>It is not about escaping your life. It is about returning to it feeling more like yourself.</blockquote><small>— THE GIFT SPA PHILOSOPHY</small></section><section className="newsletter"><div><p className="eyebrow">THE SPA LETTER</p><h2>Good things, occasionally.</h2></div><form onSubmit={e=>e.preventDefault()}><input type="email" placeholder="Email address"/><button>Subscribe <ArrowUpRight size={15}/></button></form></section></>}

function TreatmentCard({t}){return <article className="tCard"><div className="art"><span>{t[0]}</span><Sparkles/></div><div><small>{t[2]} · {t[3]}</small><h3>{t[1]}</h3><p>{t[4]}</p><Link className="under" to="/contact">Enquire <ArrowUpRight size={14}/></Link></div></article>}

function Treatments(){return <Page title="Treatments" kicker="THE MENU" intro="Restorative treatments with a little more intention. Choose one for yourself, or make someone else's day."><div className="cards treatmentsGrid">{treatments.map(t=><TreatmentCard key={t[0]} t={t}/>)}</div><section className="infoStrip"><div><Clock/><h3>Before your visit</h3><p>Arrive 15 minutes early. Your treatment begins with a quiet consultation so we can tailor the experience to you.</p></div><div><Heart/><h3>For every body</h3><p>Tell us about any preferences, accessibility needs or sensitivities when you book.</p></div><div><CalendarDays/><h3>Easy booking</h3><p>Need a different time? Contact our guest team and we will find a better moment.</p></div></section></Page>}

function Gifting(){return <Page title="Gifting" kicker="GIVE TIME" intro="A beautiful way to say thank you, happy birthday, I miss you, or simply take a breath."><div className="giftGrid">{gifts.map((g,i)=><article className="giftCard" key={g[0]}><div className="giftNo">0{i+1}</div><Gift/><h3>{g[0]}</h3><strong>{g[1]}</strong><p>{g[2]}</p><button className="under">Choose this gift <ArrowUpRight size={14}/></button></article>)}</div><div className="giftNote"><div><p className="eyebrow">DIGITAL & PHYSICAL</p><h2>Made for last-minute thinkers.</h2></div><p>Send a digital gift card in minutes, or request a beautifully presented physical card for a more tangible moment. Every gift is valid for 12 months.</p></div></Page>}

function Wellness(){return <Page title="Wellness" kicker="BEYOND THE TREATMENT" intro="Small rituals that make a noticeable difference. Practical wellness, beautifully considered."><div className="wellGrid">{[['01','Sleep','A softer evening starts before bed. Explore our wind-down ritual and simple sleep cues.'],['02','Movement','Gentle movement, breath and body awareness for people who spend too much time sitting still.'],['03','Skin','Understand your skin, simplify your routine and make space for the products that actually serve you.'],['04','Mind','Five-minute practices for busy minds, from grounding to guided breathing.']].map(x=><article><span>{x[0]}</span><h3>{x[1]}</h3><p>{x[2]}</p><Link className="under" to="/journal">Read the journal <ArrowUpRight size={14}/></Link></article>)}</div></Page>}

function About(){return <Page title="About Gift Spa" kicker="OUR STORY" intro="A calm space in a busy city, built around a simple idea: care is one of the most generous things we can give."><section className="story"><div className="storyVisual"><span>EST. 2026<br/>LONDON</span></div><div><p>Gift Spa began with a question: what if a spa could feel less like a service and more like a pause?</p><p>We designed every part of the experience around that pause. Natural textures. Quiet transitions. Expert practitioners. No pressure to buy more, do more or be more.</p><p>Just thoughtful care, delivered well.</p><Link className="primary" to="/contact">Come and see us <ArrowUpRight size={16}/></Link></div></section></Page>}

function Gallery(){return <Page title="Gallery" kicker="THE SPACE" intro="A visual diary of rituals, details and the quieter side of city life."><div className="gallery">{Array.from({length:8},(_,i)=><div className={'galleryItem g'+i} key={i}><span>{['Treatment room','Botanical details','Slow mornings','The gift edit','Tea ritual','Soft light','A moment to yourself','Gift Spa'][i]}</span></div>)}</div></Page>}

function Journal(){const posts=[['The art of doing less','WELLNESS · 6 MIN','Why intentional rest can be more useful than another productivity hack.'],['How to choose a spa gift','GIFTING · 4 MIN','A simple guide to giving someone a treatment they will actually love.'],['Your first treatment','THE SPA · 5 MIN','What to expect before, during and after your first visit.'],['The evening reset','RITUALS · 3 MIN','A five-minute routine for turning down the volume on a busy day.']];return <Page title="Journal" kicker="NOTES FROM THE SPA" intro="Ideas for slower living, better gifting and making room for yourself."><div className="journal">{posts.map((p,i)=><article><div className="postArt">{String(i+1).padStart(2,'0')}</div><div><small>{p[1]}</small><h3>{p[0]}</h3><p>{p[2]}</p><Link className="under" to={'/journal/'+i}>Read story <ArrowUpRight size={14}/></Link></div></article>)}</div></Page>}

function Media(){return <Page title="Media" kicker="PRESS & PARTNERS" intro="Brand assets, press notes and information for journalists, creators and partners."><div className="mediaGrid"><div><p className="eyebrow">PRESS ENQUIRIES</p><h2>For stories about modern wellness, gifting and hospitality.</h2><p>We can provide interviews, brand imagery, founder commentary and treatment experiences for relevant editorial features.</p><a className="primary" href="mailto:press@giftspa.co.uk">Contact press <Mail size={16}/></a></div><div className="mediaList">{['Press kit 2026','Brand story & factsheet','Logo & identity assets','Photography library'].map((x,i)=><a href="#" onClick={e=>e.preventDefault()}><span>0{i+1}</span>{x}<ArrowUpRight size={15}/></a>)}</div></div></Page>}

function Contact(){return <Page title="Contact" kicker="COME BY" intro="Questions, accessibility requests, group visits or simply not sure where to start? We are here."><div className="contactGrid"><div className="contactDetails"><div><MapPin/><h3>Find us</h3><p>42 Rose Lane<br/>London, UK</p></div><div><Clock/><h3>Opening hours</h3><p>Monday — Sunday<br/>09:00 — 20:00</p></div><div><Mail/><h3>Email</h3><p>hello@giftspa.co.uk</p></div><div><Phone/><h3>Phone</h3><p>+44 20 7946 0880</p></div></div><form className="contactForm" onSubmit={e=>{e.preventDefault();e.currentTarget.innerHTML='<h2>Thank you.</h2><p>Your message has been received. We will be in touch shortly.</p>'}}><input required placeholder="Name"/><input required type="email" placeholder="Email"/><select><option>What can we help with?</option><option>Booking</option><option>Gift cards</option><option>Group visit</option><option>Press / partnership</option><option>Other</option></select><textarea required rows="6" placeholder="Your message"></textarea><button className="primary">Send enquiry <ArrowUpRight size={16}/></button></form></div></Page>}

function FAQ(){const[active,setActive]=useState(0);const qs=['How far in advance should I book?','Can I change or cancel my booking?','Do you offer treatments for pregnancy?','How do gift cards work?','Is Gift Spa accessible?','Can I book for a group?'];return <Page title="FAQs" kicker="HELP CENTRE" intro="A few useful answers before your visit. If you cannot find what you need, contact the guest team."><div className="faq">{qs.map((q,i)=><div className={active===i?'active':''}><button onClick={()=>setActive(active===i?-1:i)}><span>{q}</span><ChevronDown/></button>{active===i&&<p>{i===3?'Gift cards are available digitally and can be used against eligible treatments for 12 months.':'We are happy to help. Our guest team will confirm the details with you and make sure your visit is comfortable and straightforward.'}</p>}</div>)}</div></Page>}

function Legal({title,text}){return <Page title={title} kicker="GIFT SPA"><div className="legal"><h3>Our commitment</h3><p>{text}</p><h3>Using this website</h3><p>This demonstration site is designed as production-ready source code for a UK spa brand. Information, prices and availability should be confirmed by the business before launch.</p><h3>Questions</h3><p>For any question about this notice, contact hello@giftspa.co.uk.</p></div></Page>}

function Page({title,kicker,children,intro}){return <><section className="pageHero"><p className="eyebrow">{kicker}</p><h1>{title}</h1>{intro&&<p>{intro}</p>}</section><section className="pageBody">{children}</section></>}

function App(){let path=location.pathname.replace(/\/$/,'')||'/';let C=path==='/'?Home:path==='/treatments'?Treatments:path==='/gifting'?Gifting:path==='/wellness'?Wellness:path==='/about'?About:path==='/gallery'?Gallery:path==='/journal'?Journal:path==='/media'?Media:path==='/contact'?Contact:path==='/faqs'?FAQ:path==='/privacy'?()=> <Legal title="Privacy" text="We only collect information you choose to provide through enquiries or booking requests. We do not sell personal information."/>:path==='/terms'?()=> <Legal title="Terms" text="Bookings, gift cards and treatments are subject to availability and the final terms provided at the point of purchase."/>:path==='/accessibility'?()=> <Legal title="Accessibility" text="We aim to make every visit and digital experience welcoming and accessible. Please tell us what support you need."/>:Contact;return <Layout><C/></Layout>}createRoot(document.getElementById('root')).render(<App/>);